USE [master]
GO
CREATE DATABASE [INTEGRADORNET]
GO
USE [INTEGRADORNET]
GO
[dbo].[PRODUCTO]

/****** Object:  Table [dbo].[CLIENTEEMPRESA]    Script Date:  ******/
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[CLIENTEEMPRESA]') AND type in (N'U'))
DROP TABLE [dbo].[CLIENTEEMPRESA]
GO

/****** Object:  Table [dbo].[CLIENTEINDIVIDUO]    Script Date:  ******/
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[CLIENTEINDIVIDUO]') AND type in (N'U'))
DROP TABLE [dbo].CLIENTEINDIVIDUO
GO

/****** Object:  Table [dbo].[PRODUCTO]    Script Date:  ******/
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[PRODUCTO]') AND type in (N'U'))
DROP TABLE [dbo].PRODUCTO
GO

/****** Object:  Table [dbo].[VENDEDOR]    Script Date:  ******/
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[VENDEDOR]') AND type in (N'U'))
DROP TABLE [dbo].VENDEDOR
GO

/****** Object:  Table [dbo].[USUARIO]    Script Date:  ******/
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[USUARIO]') AND type in (N'U'))
DROP TABLE [dbo].USUARIO
GO


/****** Object:  Table [dbo].[CLIENTESEMPRESA]    Script Date:  ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[CLIENTEEMPRESA](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[NOMBRE] [nvarchar](100) NULL,
	[CONTACTO] [nvarchar](100) NULL,
	[CUIT] [nvarchar](13) NULL,
	[MAIL] [nvarchar](30) NULL,
	[TELEFONO] [nvarchar](15) NULL,
	[DIRECCION] [nvarchar](100) NULL,
	)ON [PRIMARY]
GO


/****** Object:  Table [dbo].[CLIENTEINDIVIDUO]    Script Date:  ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[CLIENTEINDIVIDUO](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[NOMBRE] [nvarchar](100) NULL,
	[APELLIDO] [nvarchar](100) NULL,
	[CUIT] [nvarchar](13) NULL,
	[MAIL] [nvarchar](30) NULL,
	[TELEFONO] [nvarchar](15) NULL,
	[DIRECCION] [nvarchar](100) NULL,
	)ON [PRIMARY]
GO


/****** Object:  Table [dbo].[VENDEDOR]    Script Date:  ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[VENDEDOR](
	[ID_VENDEDOR] [int] IDENTITY(1,1) NOT NULL,
	[NOMBRE] [nvarchar](100) NULL,
	[APELLIDO] [nvarchar](100) NULL,
	[DNI] [nvarchar](8) NOT NULL,
	[CUIT] [nvarchar](13) NOT NULL
) ON [PRIMARY]
GO


/****** Object:  Table [dbo].[PRODUCTO]    Script Date:  ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[PRODUCTO](
	[ID_PRODUCTO] [int] IDENTITY(1,1) NOT NULL,
	[NOMBRE] [nvarchar](60) NOT NULL,
	[DESCRIPCION] [nvarchar](150) NOT NULL,
	[PRECIOCOSTO] [money] NOT NULL,
	[MARGEN] [decimal](10, 2) NOT NULL,
	[IVA] [int] NOT NULL,
	[PRECIOBRUTO] [money] NOT NULL,
	[PRECIOVENTA] [money] NOT NULL,
	[PROVEEDOR] [nvarchar](100) NOT NULL,
	[CATEGORIA] [nvarchar](15) NOT NULL,
	[SUBCATEGORIA] [nvarchar](20) NOT NULL,
) ON [PRIMARY]
GO


/****** Object:  Table [dbo].[USUARIO]    Script Date:  ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[USUARIO](
	
	[LOGIN] [nvarchar](50) NOT NULL,
	[APELLYNOM] [nvarchar](150) NOT NULL,
	[PASSW] [nvarchar](10) NOT NULL,
	[FCH_ALTA] [smalldatetime] NOT NULL,
	[FCH_BAJA] [smalldatetime] NULL,
) ON [PRIMARY]
GO


INSERT [dbo].[CLIENTEEMPRESA] ([NOMBRE], [CONTACTO], [CUIT], [MAIL], [TELEFONO], [DIRECCION])
VALUES ('GRUPO ARCOR', 'POZO CAÑADA', '30-00001111-1', 'GRUPOARCOR@CORREO.COM', '88856342', 'AV. SANTA FE 645')
GO
INSERT [dbo].[CLIENTEEMPRESA] ([NOMBRE], [CONTACTO], [CUIT], [MAIL], [TELEFONO], [DIRECCION])
VALUES ('DESPEGAR', 'ALCANTAR JOSE', '30-00002222-2', 'DESPEGAR@CORREO.COM', '57492034', 'AV. CORDOBA 34')
GO
INSERT [dbo].[CLIENTEEMPRESA] ([NOMBRE], [CONTACTO], [CUIT], [MAIL], [TELEFONO], [DIRECCION])
VALUES ('WALMART', 'ARIAS JAVIER', '30-00003333-1', 'WALMART@CORREO.COM', '85936475', 'AV. MITRE 3456')
GO
INSERT [dbo].[CLIENTEEMPRESA] ([NOMBRE], [CONTACTO], [CUIT], [MAIL], [TELEFONO], [DIRECCION])
VALUES ('YPF', 'ARREDONDO LEONARDO', '30-00004444-1', 'YPF@CORREO.COM', '47583673', 'AV. SAN MARTIN 3547')
GO
INSERT [dbo].[CLIENTEEMPRESA] ([NOMBRE], [CONTACTO], [CUIT], [MAIL], [TELEFONO], [DIRECCION])
VALUES ('TELEFONICA', 'GARCIA FAUSTO', '30-00005555-2', 'TELEFONICA@CORREO.COM', '76021749', 'AV. COMODORO PY 1900')
GO
INSERT [dbo].[CLIENTEEMPRESA] ([NOMBRE], [CONTACTO], [CUIT], [MAIL], [TELEFONO], [DIRECCION])
VALUES ('COTO', 'HUCHANSKY INES', '30-00006666-1', 'COTO@CORREO.COM', '26374953', 'AV. SOLANO 987')
GO
INSERT [dbo].[CLIENTEEMPRESA] ([NOMBRE], [CONTACTO], [CUIT], [MAIL], [TELEFONO], [DIRECCION])
VALUES ('FARMACITY', 'IBAÑEZ ROBERTO', '30-00007777-2', 'FARMACITY@CORREO.COM', '27394475', 'AV. BEIRO 2734')
GO
INSERT [dbo].[CLIENTEEMPRESA] ([NOMBRE], [CONTACTO], [CUIT], [MAIL], [TELEFONO], [DIRECCION])
VALUES ('SANTANDER RIO', 'EDEN ATELLA MARIS', '30-00008888-1', 'SANTANDERRIO@CORREO.COM', '12739472', 'AV. PERON 125')
GO
INSERT [dbo].[CLIENTEEMPRESA] ([NOMBRE], [CONTACTO], [CUIT], [MAIL], [TELEFONO], [DIRECCION])
VALUES ('MERCADO LIBRE', 'FUENTES EDGARDO', '30-00009999-1', 'MERCADOLIBRE@CORREO.COM', '38119926', 'AV. CORRIENTES 3729')
GO



INSERT [dbo].[CLIENTEINDIVIDUO] ([NOMBRE], [APELLIDO], [CUIT], [MAIL], [TELEFONO], [DIRECCION])
VALUES ('ZORAIDA', 'CEPEDA', '27-11111111-6', 'ZORAIDA.CEPEDA@GMAIL.COM', '31118258', 'AV.PTE. PERON 423')
GO
INSERT [dbo].[CLIENTEINDIVIDUO] ([NOMBRE], [APELLIDO], [CUIT], [MAIL], [TELEFONO], [DIRECCION])
VALUES ('RAMON', 'BASSOL', '26-22222222-4', 'RAMON.BASSOL@GMAIL.COM', '25364794', 'CCBULNES 1234')
GO
INSERT [dbo].[CLIENTEINDIVIDUO] ([NOMBRE], [APELLIDO], [CUIT], [MAIL], [TELEFONO], [DIRECCION])
VALUES ('CAROLA', 'CERVANTES', '27-33333333-6', 'CAROLA.CERVANTES@HOTMAIL.COM', '36729472', 'SAAVEDRA S/N')
GO
INSERT [dbo].[CLIENTEINDIVIDUO] ([NOMBRE], [APELLIDO], [CUIT], [MAIL], [TELEFONO], [DIRECCION])
VALUES ('ROXANA', 'BARBIER', '27-44444444-6', 'ROXANA.BARBIER@GMAIL.COM', '64538263', 'JURAMENTO 2349')
GO
INSERT [dbo].[CLIENTEINDIVIDUO] ([NOMBRE], [APELLIDO], [CUIT], [MAIL], [TELEFONO], [DIRECCION])
VALUES ('MAXIMILIANO', 'HERAS', '26-55555555-4', 'MAXIMILIANO.HERAS@HOTMAIL.COM', '36485621', 'ALICIA MOREAU DE JUSTO 775')
GO
INSERT [dbo].[CLIENTEINDIVIDUO] ([NOMBRE], [APELLIDO], [CUIT], [MAIL], [TELEFONO], [DIRECCION])
VALUES ('LUIS', 'ALAS', '26-66666666-4', 'LUIS.ALAS@GMAIL.COM', '31936244', 'CARLOS PEÑALOZA 45')
GO
INSERT [dbo].[CLIENTEINDIVIDUO] ([NOMBRE], [APELLIDO], [CUIT], [MAIL], [TELEFONO], [DIRECCION])
VALUES ('GERARDO', 'BRIONES', '26-77777777-4', 'GERARDO.BRIONES@YAHOO.COM', '42899446', 'AV. 30 DE SEPTIEMBRE 146')
GO
INSERT [dbo].[CLIENTEINDIVIDUO] ([NOMBRE], [APELLIDO], [CUIT], [MAIL], [TELEFONO], [DIRECCION])
VALUES ('SUSANA', 'GOMEZ', '27-88888888-6', 'SUSANA.GOMEZ@YAHOO.COM', '34216445', 'AV. CORDOBA 23')
GO
INSERT [dbo].[CLIENTEINDIVIDUO] ([NOMBRE], [APELLIDO], [CUIT], [MAIL], [TELEFONO], [DIRECCION])
VALUES ('SIMON', 'DIAZ', '27-99999999-6', 'SIMON.DIAZ@GMAIL.COM', '24377765', 'SIMBRON 3524')
GO



INSERT [dbo].[VENDEDOR] ([NOMBRE], [APELLIDO], [DNI], [CUIT])
VALUES ('JOSE', 'MERCADO', '43258441', '20-43258441-5')
GO
INSERT [dbo].[VENDEDOR] ([NOMBRE], [APELLIDO], [DNI], [CUIT])
VALUES ('MARIA', 'DELGADO', '40587266', '27-40587266-6')
GO
INSERT [dbo].[VENDEDOR] ([NOMBRE], [APELLIDO], [DNI], [CUIT])
VALUES ('CARLOS', 'DIAZ', '38447710', '23-38447710-5')
GO



INSERT [dbo].[PRODUCTO] ([NOMBRE], [DESCRIPCION], [PRECIOCOSTO], [MARGEN], [IVA], [PRECIOBRUTO], [PRECIOVENTA], [PROVEEDOR], [CATEGORIA], [SUBCATEGORIA])
VALUES ('MONITOR VIEWSONIC', 'LED 20" 60HZ VGA DVI VA2055SM', 53695.75, 23012.46, 20390.79, 76708.21, 97099, 'ADISTEC', 'CATEGORIA A', 'SUBCATEGORIA A.A')
GO
INSERT [dbo].[PRODUCTO] ([NOMBRE], [DESCRIPCION], [PRECIOCOSTO], [MARGEN], [IVA], [PRECIOBRUTO], [PRECIOVENTA], [PROVEEDOR], [CATEGORIA], [SUBCATEGORIA])
VALUES ('MONITOR ASUS', ' LED 24" FULL HD IPS 75HZ 5MS FREESYNC VA24EHE-J', 93191.01, 39939.00, 35388.99, 133130.01, 168519, 'ADISTEC', 'CATEGORIA A', 'SUBCATEGORIA B.C')
GO
INSERT [dbo].[PRODUCTO] ([NOMBRE], [DESCRIPCION], [PRECIOCOSTO], [MARGEN], [IVA], [PRECIOBRUTO], [PRECIOVENTA], [PROVEEDOR], [CATEGORIA], [SUBCATEGORIA])
VALUES ('MEMORIA RAM', 'DDR4 - 8GB 3200 MHZ CORSAIR VENGEANCE RGB PRO NEGRO', 19697.31, 8441.70, 7479.99, 28139.01, 35619,'AIR', 'CATEGORIA C', 'SUBCATEGORIA A.C')
GO
INSERT [dbo].[PRODUCTO] ([NOMBRE], [DESCRIPCION], [PRECIOCOSTO], [MARGEN], [IVA], [PRECIOBRUTO], [PRECIOVENTA], [PROVEEDOR], [CATEGORIA], [SUBCATEGORIA])
VALUES ('MEMORIA RAM', 'DDR4 - 8GB 3600 MHZ KINGSTON FURY RENEGADE RGB', 26438.38, 11330.73, 10039.89, 37769.11, 47809,'AIR', 'CATEGORIA C', 'SUBCATEGORIA B.A')
GO
INSERT [dbo].[PRODUCTO] ([NOMBRE], [DESCRIPCION], [PRECIOCOSTO], [MARGEN], [IVA], [PRECIOBRUTO], [PRECIOVENTA], [PROVEEDOR], [CATEGORIA], [SUBCATEGORIA])
VALUES ('PLACA DE VIDEO', 'GEFORCE RTX 4070 12GB GIGABYTE GAMING OC', 541939.45, 232259.76, 205799.79, 774199.21, 979999,'CEVEN', 'CATEGORIA B', 'SUBCATEGORIA A.B')
GO
INSERT [dbo].[PRODUCTO] ([NOMBRE], [DESCRIPCION], [PRECIOCOSTO], [MARGEN], [IVA], [PRECIOBRUTO], [PRECIOVENTA], [PROVEEDOR], [CATEGORIA], [SUBCATEGORIA])
VALUES ('PLACA DE VIDEO', 'GEFORCE GT 1030 2GB MSI OC', 67426.74, 28897.17, 25605.09, 96323.91, 121929,'CEVEN', 'CATEGORIA B', 'SUBCATEGORIA C.A')
GO
INSERT [dbo].[PRODUCTO] ([NOMBRE], [DESCRIPCION], [PRECIOCOSTO], [MARGEN], [IVA], [PRECIOBRUTO], [PRECIOVENTA], [PROVEEDOR], [CATEGORIA], [SUBCATEGORIA])
VALUES ('IMPRESORA EPSON', 'L3210 CONTINUA MULTIFUNCIÓN', 210117.33, 90050.28, 79791.39, 300167.61, 379959,'CORCISA', 'CATEGORIA A', 'SUBCATEGORIA A.B')
GO
INSERT [dbo].[PRODUCTO] ([NOMBRE], [DESCRIPCION], [PRECIOCOSTO], [MARGEN], [IVA], [PRECIOBRUTO], [PRECIOVENTA], [PROVEEDOR], [CATEGORIA], [SUBCATEGORIA])
VALUES ('IMPRESORA EPSON', 'L8160 CONTINUA MULTIFUNCIÓN + PACK X4 TINTA ORIGINAL', 511955.79, 219409.62, 194413.59, 731365.41,925779, 'CORCISA', 'CATEGORIA A', 'SUBCATEGORIA A.C')
GO
INSERT [dbo].[PRODUCTO] ([NOMBRE], [DESCRIPCION], [PRECIOCOSTO], [MARGEN], [IVA], [PRECIOBRUTO], [PRECIOVENTA], [PROVEEDOR], [CATEGORIA], [SUBCATEGORIA])
VALUES ('CÁMARA WEB', 'REDRAGON GW800-1 HITMAN 1080P', 21466.91, 9200.10, 8151.99, 30667.01, 38819,'DACAS', 'CATEGORIA B', 'SUBCATEGORIA B.A')
GO
INSERT [dbo].[PRODUCTO] ([NOMBRE], [DESCRIPCION], [PRECIOCOSTO], [MARGEN], [IVA], [PRECIOBRUTO], [PRECIOVENTA], [PROVEEDOR], [CATEGORIA], [SUBCATEGORIA])
VALUES ('CÁMARA IP', 'CLOUD TP-LINK TAPO C320WS SD WIFI EXTERIOR', 71889.45, 30809.76, 27299.79, 102699.21, 129999,'DACAS', 'CATEGORIA B', 'SUBCATEGORIA B.B')
GO
INSERT [dbo].[PRODUCTO] ([NOMBRE], [DESCRIPCION], [PRECIOCOSTO], [MARGEN], [IVA], [PRECIOBRUTO], [PRECIOVENTA], [PROVEEDOR], [CATEGORIA], [SUBCATEGORIA])
VALUES ('DISCO RIGIDO', '1TB SEAGATE SKYHAWK', 60635.90, 25986.81, 23026.29, 86622.71, 109649,'DISTECNA', 'CATEGORIA C', 'SUBCATEGORIA B.C')
GO
INSERT [dbo].[PRODUCTO] ([NOMBRE], [DESCRIPCION], [PRECIOCOSTO], [MARGEN], [IVA], [PRECIOBRUTO], [PRECIOVENTA], [PROVEEDOR], [CATEGORIA], [SUBCATEGORIA])
VALUES ('DISCO RIGIDO', '6TB SEAGATE SKYHAWK', 181084.83, 77607.78, 68766.39, 258692.61, 327459,'DISTECNA', 'CATEGORIA C', 'SUBCATEGORIA C.A')
GO
INSERT [dbo].[PRODUCTO] ([NOMBRE], [DESCRIPCION], [PRECIOCOSTO], [MARGEN], [IVA], [PRECIOBRUTO], [PRECIOVENTA], [PROVEEDOR], [CATEGORIA], [SUBCATEGORIA])
VALUES ('ESCANER BROTHER', 'DESKTOP ADS-2200', 223726.66, 95882.85, 84959.49, 319609.51, 404569,'ELIT', 'CATEGORIA A', 'SUBCATEGORIA C.B')
GO
INSERT [dbo].[PRODUCTO] ([NOMBRE], [DESCRIPCION], [PRECIOCOSTO], [MARGEN], [IVA], [PRECIOBRUTO], [PRECIOVENTA], [PROVEEDOR], [CATEGORIA], [SUBCATEGORIA])
VALUES ('ESCANER BROTHER', 'DESKTOP ADS-1250W', 207407.63, 88888.98, 78762.39, 296296.61, 375059,'ELIT', 'CATEGORIA A', 'SUBCATEGORIA C.C')
GO
 

INSERT [dbo].[USUARIO] ([LOGIN], [APELLYNOM], [PASSW], [FCH_ALTA], [FCH_BAJA])
VALUES ('SA', 'SA', 'CLASE2023', '2023-01-01 00:00:00', NULL)
GO
INSERT [dbo].[USUARIO] ([LOGIN], [APELLYNOM], [PASSW], [FCH_ALTA], [FCH_BAJA])
VALUES ('ADMIN', 'ADMIN', '12345678', '2023-02-01 00:00:00', NULL)
GO
INSERT [dbo].[USUARIO] ([LOGIN], [APELLYNOM], [PASSW], [FCH_ALTA], [FCH_BAJA])
VALUES ('PSUAREZ', 'PATRICIO SUAREZ', 'CLASE', '2023-03-01 00:00:00', NULL)
GO

